/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.core.HolderLookup$Provider
 *  net.minecraft.data.PackOutput
 *  net.minecraft.data.recipes.RecipeCategory
 *  net.minecraft.data.recipes.RecipeOutput
 *  net.minecraft.data.recipes.RecipeProvider
 *  net.minecraft.data.recipes.ShapedRecipeBuilder
 *  net.minecraft.data.recipes.ShapelessRecipeBuilder
 *  net.minecraft.data.recipes.SimpleCookingRecipeBuilder
 *  net.minecraft.data.recipes.SingleItemRecipeBuilder
 *  net.minecraft.data.recipes.SmithingTransformRecipeBuilder
 *  net.minecraft.world.item.Item
 *  net.minecraft.world.item.Items
 *  net.minecraft.world.item.crafting.Ingredient
 *  net.minecraft.world.level.ItemLike
 *  net.minecraft.world.level.block.Block
 *  net.minecraft.world.level.block.Blocks
 *  net.neoforged.neoforge.common.conditions.IConditionBuilder
 *  net.neoforged.neoforge.registries.DeferredBlock
 */
package com.perigrine3.createcybernetics.datagen;

import com.perigrine3.createcybernetics.block.ModBlocks;
import com.perigrine3.createcybernetics.item.ModItems;
import com.perigrine3.createcybernetics.util.ModTags;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.RecipeCategory;
import net.minecraft.data.recipes.RecipeOutput;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.data.recipes.ShapedRecipeBuilder;
import net.minecraft.data.recipes.ShapelessRecipeBuilder;
import net.minecraft.data.recipes.SimpleCookingRecipeBuilder;
import net.minecraft.data.recipes.SingleItemRecipeBuilder;
import net.minecraft.data.recipes.SmithingTransformRecipeBuilder;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.conditions.IConditionBuilder;
import net.neoforged.neoforge.registries.DeferredBlock;

public class ModRecipeProvider
extends RecipeProvider
implements IConditionBuilder {
    public ModRecipeProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> registries) {
        super(output, registries);
    }

    protected void buildRecipes(RecipeOutput recipeOutput) {
        List<DeferredBlock<Block>> TITANIUM_SMELTABLES = List.of(ModItems.RAWTITANIUM, ModItems.CRUSHEDTITANIUM, ModBlocks.TITANIUMORE_BLOCK, ModBlocks.DEEPSLATE_TITANIUMORE_BLOCK);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.TITANIUM_BLOCK.get())).pattern("TTT").pattern("TTT").pattern("TTT").define(Character.valueOf('T'), (ItemLike)ModItems.TITANIUMINGOT.get()).unlockedBy("has_titaniumingot", ModRecipeProvider.has(ModItems.TITANIUMINGOT)).save(recipeOutput);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER.get())).pattern("TTT").pattern("TCT").pattern("TTT").define(Character.valueOf('T'), (ItemLike)ModItems.TITANIUMINGOT.get()).define(Character.valueOf('C'), (ItemLike)Blocks.COPPER_BLOCK).unlockedBy("has_titaniumingot", ModRecipeProvider.has(ModItems.TITANIUMINGOT)).unlockedBy("has_copper_block", ModRecipeProvider.has((ItemLike)Blocks.COPPER_BLOCK)).save(recipeOutput);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.RAW_TITANIUM_BLOCK.get())).pattern("TTT").pattern("TTT").pattern("TTT").define(Character.valueOf('T'), (ItemLike)ModItems.RAWTITANIUM.get()).unlockedBy("has_rawtitanium", ModRecipeProvider.has(ModItems.RAWTITANIUM)).save(recipeOutput);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.TITANIUMINGOT.get())).pattern("TTT").pattern("TTT").pattern("TTT").define(Character.valueOf('T'), (ItemLike)ModItems.TITANIUMNUGGET.get()).unlockedBy("has_titaniumnugget", ModRecipeProvider.has(ModItems.TITANIUMNUGGET)).save(recipeOutput, "createcybernetics:titaniumingot_from_titaniumnuggets");
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get())).pattern("TTT").pattern("TMT").pattern("TZT").define(Character.valueOf('M'), (ItemLike)ModItems.SKINUPGRADES_METALPLATING.get()).define(Character.valueOf('T'), (ItemLike)Items.COPPER_INGOT).define(Character.valueOf('Z'), (ItemLike)Items.COPPER_BLOCK).unlockedBy("has_metal_plating", ModRecipeProvider.has(ModItems.SKINUPGRADES_METALPLATING)).save(recipeOutput, "createcybernetics:copper_template");
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get())).pattern("TTT").pattern("TMT").pattern("TZT").define(Character.valueOf('M'), (ItemLike)ModItems.SKINUPGRADES_METALPLATING.get()).define(Character.valueOf('T'), (ItemLike)Items.IRON_INGOT).define(Character.valueOf('Z'), (ItemLike)Items.IRON_BLOCK).unlockedBy("has_metal_plating", ModRecipeProvider.has(ModItems.SKINUPGRADES_METALPLATING)).save(recipeOutput, "createcybernetics:iron_template");
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get())).pattern("TTT").pattern("TMT").pattern("TZT").define(Character.valueOf('M'), (ItemLike)ModItems.SKINUPGRADES_METALPLATING.get()).define(Character.valueOf('T'), (ItemLike)Items.GOLD_INGOT).define(Character.valueOf('Z'), (ItemLike)Items.GOLD_BLOCK).unlockedBy("has_metal_plating", ModRecipeProvider.has(ModItems.SKINUPGRADES_METALPLATING)).save(recipeOutput, "createcybernetics:gold_template");
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.TITANIUMINGOT.get()), (int)9).requires((ItemLike)ModBlocks.TITANIUM_BLOCK.get()).unlockedBy("has_titanium_block", ModRecipeProvider.has(ModBlocks.TITANIUM_BLOCK)).save(recipeOutput, "createcybernetics:titaniumingot_from_titanium_block");
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.RAWTITANIUM.get()), (int)9).requires((ItemLike)ModBlocks.RAW_TITANIUM_BLOCK.get()).unlockedBy("has_titanium_block", ModRecipeProvider.has(ModBlocks.RAW_TITANIUM_BLOCK)).save(recipeOutput, "createcybernetics:rawtitanium_from_raw_titanium_block");
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.TITANIUMNUGGET.get()), (int)9).requires((ItemLike)ModItems.TITANIUMINGOT.get()).unlockedBy("has_titaniumingot", ModRecipeProvider.has(ModItems.TITANIUMINGOT)).save(recipeOutput, "createcybernetics:titaniumnugget_from_titaniumingot");
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.ANDOUILLE_SAUSAGE.get()), (int)4).requires((ItemLike)ModItems.GROUND_OFFAL.get()).requires((ItemLike)ModItems.BODYPART_INTESTINES.get()).unlockedBy("has_ground_offal", ModRecipeProvider.has(ModItems.GROUND_OFFAL)).unlockedBy("has_intestines", ModRecipeProvider.has(ModItems.BODYPART_INTESTINES)).save(recipeOutput, "createcybernetics:andouille_sausage_recipe");
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.GROUND_OFFAL.get()), (int)4).pattern("OOO").pattern("OOO").define(Character.valueOf('O'), ModTags.Items.OFFAL).unlockedBy("has_offal", ModRecipeProvider.has(ModTags.Items.OFFAL)).save(recipeOutput, "createcybernetics:ground_offal_recipe");
        ModRecipeProvider.oreSmelting((RecipeOutput)recipeOutput, TITANIUM_SMELTABLES, (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.TITANIUMINGOT.get()), (float)0.25f, (int)200, (String)"titanium");
        ModRecipeProvider.oreBlasting((RecipeOutput)recipeOutput, TITANIUM_SMELTABLES, (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModItems.TITANIUMINGOT.get()), (float)0.25f, (int)100, (String)"titanium");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.TITANIUM_BLOCK.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM.get()), (int)4).unlockedBy("has_titanium_block", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.TITANIUM_BLOCK.get()))).save(recipeOutput, "createcybernetics:smooth_titanium_from_stonecutter");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.SMOOTH_TITANIUM.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM_STAIRS.get()), (int)2).unlockedBy("has_smooth_titanium", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM.get()))).save(recipeOutput, "createcybernetics:smooth_titanium_stairs_from_stonecutter");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.SMOOTH_TITANIUM.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM_SLAB.get()), (int)2).unlockedBy("has_smooth_titanium", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM.get()))).save(recipeOutput, "createcybernetics:smooth_titanium_slab_from_stonecutter");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.SMOOTH_TITANIUM.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.TITANIUM_GRATE.get()), (int)4).unlockedBy("has_smooth_titanium", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM.get()))).save(recipeOutput, "createcybernetics:titanium_grate_from_stonecutter");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.TITANIUM_CLAD_COPPER.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER.get()), (int)4).unlockedBy("has_titanium_clad_copper", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER.get()))).save(recipeOutput, "createcybernetics:etched_titanium_from_stonecutter");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER_STAIRS.get()), (int)2).unlockedBy("has_etched_titanium_copper", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER.get()))).save(recipeOutput, "createcybernetics:etched_titanium_stairs_from_stonecutter");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER_SLAB.get()), (int)2).unlockedBy("has_etched_titanium_copper", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER.get()))).save(recipeOutput, "createcybernetics:etched_titanium_slab_from_stonecutter");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.TITANIUM_CLAD_COPPER.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER_STAIRS.get()), (int)2).unlockedBy("has_titanium_clad_copper", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER.get()))).save(recipeOutput, "createcybernetics:titanium_clad_copper_stairs_from_stonecutter");
        SingleItemRecipeBuilder.stonecutting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModBlocks.TITANIUM_CLAD_COPPER.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER_SLAB.get()), (int)2).unlockedBy("has_titanium_clad_copper", ModRecipeProvider.has((ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER.get()))).save(recipeOutput, "createcybernetics:titanium_clad_copper_slab_from_stonecutter");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{ModItems.TITANIUMSHEET}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.XP_CAPSULE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.COMPONENT_WIRING.get()}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BRAINUPGRADES_CORTICALSTACK.get())).unlocks("has_xp_capsule", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.XP_CAPSULE.get()))).save(recipeOutput, "createcybernetics:cortical_stack_from_xp_capsule");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_LEFTARM.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.COPPER_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_LEFTARM_COPPERPLATED.get())).unlocks("has_copper_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:copperplated_leftarm");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_RIGHTARM.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.COPPER_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_RIGHTARM_COPPERPLATED.get())).unlocks("has_copper_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:copperplated_rightarm");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_LEFTLEG.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.COPPER_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_LEFTLEG_COPPERPLATED.get())).unlocks("has_copper_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:copperplated_leftleg");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_RIGHTLEG.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.COPPER_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_RIGHTLEG_COPPERPLATED.get())).unlocks("has_copper_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.COPPER_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:copperplated_rightleg");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_LEFTARM.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_LEFTARM_IRONPLATED.get())).unlocks("has_iron_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:ironplated_leftarm");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_RIGHTARM.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_RIGHTARM_IRONPLATED.get())).unlocks("has_iron_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:ironplated_rightarm");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_LEFTLEG.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_LEFTLEG_IRONPLATED.get())).unlocks("has_iron_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:ironplated_leftleg");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_RIGHTLEG.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_RIGHTLEG_IRONPLATED.get())).unlocks("has_iron_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.IRON_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:ironplated_rightleg");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_LEFTARM.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_LEFTARM_GOLDPLATED.get())).unlocks("has_gold_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:goldplated_leftarm");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_RIGHTARM.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_RIGHTARM_GOLDPLATED.get())).unlocks("has_gold_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:goldplated_rightarm");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_LEFTLEG.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_LEFTLEG_GOLDPLATED.get())).unlocks("has_gold_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:goldplated_leftleg");
        SmithingTransformRecipeBuilder.smithing((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BASECYBERWARE_RIGHTLEG.get()}), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_INGOT}), (RecipeCategory)RecipeCategory.MISC, (Item)((Item)ModItems.BASECYBERWARE_RIGHTLEG_GOLDPLATED.get())).unlocks("has_gold_template", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.GOLD_UPGRADE_TEMPLATE.get()))).save(recipeOutput, "createcybernetics:goldplated_rightleg");
        SimpleCookingRecipeBuilder.smelting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BODYPART_BRAIN.get()}), (RecipeCategory)RecipeCategory.FOOD, (ItemLike)((ItemLike)ModItems.COOKED_BRAIN.get()), (float)0.35f, (int)200).unlockedBy("has_brain", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.BODYPART_BRAIN.get()))).save(recipeOutput, "createcybernetics:cooked_brain_from_smelting");
        SimpleCookingRecipeBuilder.smelting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BODYPART_LIVER.get()}), (RecipeCategory)RecipeCategory.FOOD, (ItemLike)((ItemLike)ModItems.COOKED_LIVER.get()), (float)0.35f, (int)200).unlockedBy("has_liver", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.BODYPART_LIVER.get()))).save(recipeOutput, "createcybernetics:cooked_liver_from_smelting");
        SimpleCookingRecipeBuilder.smelting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)ModItems.BODYPART_HEART.get()}), (RecipeCategory)RecipeCategory.FOOD, (ItemLike)((ItemLike)ModItems.COOKED_HEART.get()), (float)0.35f, (int)200).unlockedBy("has_heart", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.BODYPART_HEART.get()))).save(recipeOutput, "createcybernetics:cooked_heart_from_smelting");
        SimpleCookingRecipeBuilder.smelting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE}), (RecipeCategory)RecipeCategory.FOOD, (ItemLike)((ItemLike)ModItems.BONE_MARROW.get()), (float)0.35f, (int)200).unlockedBy("has_bone", ModRecipeProvider.has((ItemLike)Items.BONE)).save(recipeOutput, "createcybernetics:bone_marrow_from_smelting");
        SimpleCookingRecipeBuilder.smelting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{ModItems.ANDOUILLE_SAUSAGE}), (RecipeCategory)RecipeCategory.FOOD, (ItemLike)((ItemLike)ModItems.ROASTED_ANDOUILLE.get()), (float)0.35f, (int)200).unlockedBy("has_bone", ModRecipeProvider.has((ItemLike)((ItemLike)ModItems.ANDOUILLE_SAUSAGE.get()))).save(recipeOutput, "createcybernetics:roasted_andouille_from_smelting");
        ModRecipeProvider.stairBuilder((ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM_STAIRS.get()), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{ModBlocks.SMOOTH_TITANIUM})).group("titanium").unlockedBy("has_titaniumingot", ModRecipeProvider.has(ModBlocks.SMOOTH_TITANIUM)).save(recipeOutput);
        ModRecipeProvider.slab((RecipeOutput)recipeOutput, (RecipeCategory)RecipeCategory.BUILDING_BLOCKS, (ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM_SLAB.get()), (ItemLike)((ItemLike)ModBlocks.SMOOTH_TITANIUM.get()));
        ModRecipeProvider.stairBuilder((ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER_STAIRS.get()), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{ModBlocks.TITANIUM_CLAD_COPPER})).group("titanium").unlockedBy("has_titanium_clad_copper", ModRecipeProvider.has(ModBlocks.TITANIUM_CLAD_COPPER)).save(recipeOutput);
        ModRecipeProvider.slab((RecipeOutput)recipeOutput, (RecipeCategory)RecipeCategory.BUILDING_BLOCKS, (ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER_SLAB.get()), (ItemLike)((ItemLike)ModBlocks.TITANIUM_CLAD_COPPER.get()));
        ModRecipeProvider.stairBuilder((ItemLike)((ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER_STAIRS.get()), (Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{ModBlocks.ETCHED_TITANIUM_COPPER})).group("titanium").unlockedBy("has_titaniumingot", ModRecipeProvider.has(ModBlocks.ETCHED_TITANIUM_COPPER)).save(recipeOutput);
        ModRecipeProvider.slab((RecipeOutput)recipeOutput, (RecipeCategory)RecipeCategory.BUILDING_BLOCKS, (ItemLike)((ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER_SLAB.get()), (ItemLike)((ItemLike)ModBlocks.ETCHED_TITANIUM_COPPER.get()));
    }
}

